data:
  create_rawdata: False
  size: 3
  raw_filepath: "data//raw//raw_data.json"
  consumption_filepath: "data//external//total_oil_consumption_globally.csv"
  opec_filepath: "data//external//opec_price.csv"
  dataset_filepath: "data//processed//petroleum_prices.csv"

model:
  sarimax_order: [1, 1, 1]  # p, d, q
  seasonal_order: [0, 1, 1, 5]  # P, D, Q, s
  path: "models/sarimax_model.pkl"